### ISSUE TITLE
Follow main file in package.json

### ISSUE THREAD

**Issue by StarpTech** [platdesign/node-compose#7]
It is good practice to follow at first the package.json main file instead to load the default file.
This can avoid relative path issues.

e.g
` build: ./herkules` node-conpose should looking for the main file in the package section. If no package.json exists fallback to default behaviour 'index.js'

**Comment by platdesign** [comment]
Good idea, but not the most "docker-compose"-approach.

After the next patch-release `node-compose` determines the start command based on the following steps:

1. `command` attribute in image config (node-compose.yml). Thats the most "docker-compose"-way.
2. `start-script`attribute in `package.json`. The most "nodejs/npm"-way. Also best practice in most node-docker-base-images.
3. otherwise it will use `node .` The most opinionated way.

There might an additional way - maybe step 2.5 - to look for a start script in the `bin` directory of the image. Expressjs recommended a `bin` directory with a start-script. But i think three options are more than enough. ;)

**Comment by StarpTech** [comment]
This project has nothing in common with docker.  Your features should reach the nodejs developer. Don't follow too much the "docker-compose" way. But your three approaches are good.

I prefer only the first approach (configuration over convention).

**Comment by platdesign** [comment]
> This project has nothing in common with docker.

Who claims sth else? It only should be configurable the same way as **docker-compose**.

>  Your features should reach the nodejs developer, that just said.

I'll hope they do! But the `main`-attribute from `package.json` is used to resolve the main-file during requiring. If you have a package which should be executable and loadable (microservice and its loadable client) the `main`-attribute will target at the client. 

An additional idea is to check if the image has a dockerfile in CWD, parse it and read the `CMD`. This could be step 1.5.

Step 2 is for raw nodejs-devs only ;) The last one is only a "pre-fallback" before erroring.
